abstract class BaseStudent
{

}

class StudentShort extends BaseStudent
{
short_name:String
--
+initialize(Integer,String)
+init_from_student(Student):StudentShort
+to_s():String
+validate_all?: Boolean

.. Геттеры ..
+short_name():String

.. Сеттеры ..
+short_name=(String)
}

class Student extends BaseStudent {
last_name: String
first_name: String
surname: String
--
+initialize(Hash)
+from_json_str(String)
+is_name?(String): Boolean
+get_info(): String
+short_name(): String
+find_git(): String
+to_hash(): Hash
+to_json_str(): String
+to_s(): String

    .. Геттеры ..
+last_name(): String
+first_name(): String
+surname(): String

    .. Сеттеры ..
+last_name=(): String
+first_name=(): String
+surname=(): String
}
